name: Deploy Hexo site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Setup Git & SSH & known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "23.3.0"

      - name: Install Dependencies
        run: yarn install
          
      - name: Build
        run: yarn build
        
      - name: Deploy Pages
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ./node_modules/hexo-cli/bin/hexo deploy
        
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_branch: blog
#           publish_dir: ./public
#           force_orphan: true
